version: '3'
services:
  server:
    build: .
    container_name: metrics-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
      - /app/node_modules
      - ./data:/app/data
    ports:
      - '3001:3001'
